USE FIT_ALUNOS
GO

CREATE TABLE LIVRO_L (
NOME VARCHAR (100) NOT NULL
,COPIA CHAR(7) NOT NULL
,[STATUS] CHAR (10)
,CONSTRAINT PKNOMLV PRIMARY KEY (NOME, COPIA)
);

CREATE TABLE CLIENTEBIB (
IDCLI INT NOT NULL IDENTITY(1,1)
,NOME VARCHAR(100)
,TELEFONE CHAR(15)
CONSTRAINT PKCLI PRIMARY KEY (IDCLI)
);

CREATE TABLE EMPRESTIMO (
IDEMP INT NOT NULL 
,IDCLI INT NOT NULL
,NOME VARCHAR(100)
,COPIA CHAR(7)
,DATAEMPRESTIMO DATETIME
,DATADEVOLUCAOEFETIVA DATETIME
,DATADEVOLUCAOPROPOSTA DATETIME
,MULTA CHAR(10)
,CONSTRAINT PKEMPCLI FOREIGN KEY (IDCLI)
	REFERENCES CLIENTEBIB (IDCLI)
,CONSTRAINT PKNOMEMP FOREIGN KEY (NOME, COPIA)
	REFERENCES LIVRO (NOME, COPIA)
);