

CREATE TABLE PACIENTE (
IDPAC INT NOT NULL IDENTITY (1,1)
,NOMEPAC VARCHAR(100)
,TELEFONE CHAR(20)
CONSTRAINT PKPAC PRIMARY KEY (IDPAC)
);

CREATE TABLE MEDICO (
IDMED INT NOT NULL IDENTITY (1,1)
,CRM CHAR(10)
,NOME VARCHAR(100)
,ESPECIALIDADE CHAR(20)
CONSTRAINT PKMED PRIMARY KEY (IDMED)
);

CREATE TABLE SALA (
IDSAL INT NOT NULL IDENTITY(1,1)
,NUMSAL INT NOT NULL
,CONSTRAINT PKSAL PRIMARY KEY (IDSAL)
);

CREATE TABLE CONSULTA (
IDCONS INT NOT NULL IDENTITY (1,1)
,IDPAC INT NOT NULL
,IDMED INT NOT NULL
,NUMSAL INT NOT NULL
,DATAHORA DATETIME
,DURACAO TIME
,CONSTRAINT PKCONSPAC FOREIGN KEY (IDPAC)
	REFERENCES PACIENTE (IDPAC)
,CONSTRAINT PKCONSMED FOREIGN KEY (IDMED)
	REFERENCES MEDICO (IDMED)
,CONSTRAINT PKCONSSALA FOREIGN KEY (NUMSAL)
	REFERENCES SALA (IDSAL)
);