USE FIT_ALUNOS
GO

CREATE TABLE CLIENTE_C (
IDCLI INT NOT NULL IDENTITY (1,1)
, NOMECLI VARCHAR(100) NOT NULL
, TELEFONECLI VARCHAR(20) NOT NULL
,CONSTRAINT PKCLIEN PRIMARY KEY (IDCLI)
);

CREATE TABLE PRODUTOS_P (
IDPROD INT NOT NULL IDENTITY (1,1)
,NOMEPROD VARCHAR (60)
,CONSTRAINT PKPROD PRIMARY KEY (IDPROD)
);

CREATE TABLE PEDIDO_P (
NUMPED INT NOT NULL
,IDCLI INT NOT NULL
,DATAHORA DATETIME
,CONSTRAINT PKPED PRIMARY KEY (NUMPED)
,CONSTRAINT FKPEDCLI FOREIGN KEY (IDCLI)
	REFERENCES PRODUTOS_P(IDPROD)
);

CREATE TABLE ITEM_PEDIDO (
NUMPED INT NOT NULL
,IDPROD INT NOT NULL
,QUANTIDADE INT NULL
,CONSTRAINT PKITEMPED FOREIGN KEY (NUMPED)
	REFERENCES PEDIDO_P (NUMPED)
, CONSTRAINT PKITEMPROD FOREIGN KEY (IDPROD)
	REFERENCES PRODUTOS_P (IDPROD)
);

CREATE TABLE TELEFONE_T (
IDCLI INT NOT NULL
,NUMERO1 CHAR(20)
,NUMERO2 CHAR(20)
,CONSTRAINT PKTELCLI FOREIGN KEY (IDCLI)
	REFERENCES CLIENTE_C (IDCLI)
);